### ISSUE TITLE
Bug on multilines custom fields on all apps (desktop, mobile)

### ISSUE THREAD

**Issue by vslonska** [invoiceninja/ui#2088]
Hello,
There is a bug in the apps, with multi lines custom fields. I tried it in the mobile Android app and in the snap app on linux.
![Screenshot 2024-10-03 at 12-29-30 Invoice Ninja Champs personnalises1](https://github.com/user-attachments/assets/47e99ad9-e373-4616-ad1a-1598533aeebf)

It's not possible to insert or edit a text. You just have a select input with multi_line_text written. When you go to edit the quote or invoice in the web app, you see that multi_line_text is in the field.
[Grabación de pantalla desde 2024-10-03 12-30-46_ok.webm](https://github.com/user-attachments/assets/587db5f9-0057-446b-8447-7d5323aec7ff)

If there is already a text, you can't see it in the app and you still see that select input with multi_line_text written. If you select it, it replace the text by "multi_line_text".
![Screenshot 2024-10-03 at 12-36-32 Invoice Ninja Edit Quote2](https://github.com/user-attachments/assets/360984e7-00e1-47fb-af86-9d7ca07b0b6e)

Thank you,
Regards,

**Comment by turbo124** [comment]
This should be resolved in the latest release.

**Comment by vslonska** [comment]
Hello,
Unfortunately no, the bug is still here in v5.10.30 and we can't edit or use the multi lines custom fields in the desktop and mobile apps.
Thanks,

**Comment by turbo124** [comment]
I would suggest resaving these fields as another type and then back again (from the desktop app) this will reset the column to be compatible with the desktop app.

**Comment by vslonska** [comment]
I confirm that resaving these fields as another type and then back again from the app works.
Thanks !
