### ISSUE TITLE
Tax not rounding up correctly

### ISSUE THREAD

**Issue by alexgauvin** [invoiceninja/ui#2472]
## Setup
- Version: v5.11.62 | Selfhost on shared environment

## Interface
- Both: []

## Describe the bug
Invoicing in and from Canada, one of the 2 taxes holds 3 digits after comma (9.975%)
But calculation is not always rounding up correctly, as it is for this invoice

![Image](https://github.com/user-attachments/assets/05bcfb77-4cc0-4499-9c48-3be13efd37da)
Total should display $ 344.93 = 300 + (5% + 9.975%) $ 44.925 (rounded up to 44.93%)

Strangely, tax percentage display is not consistent across pages in both UIs and across multiple edit screen. See below in React. 

![Image](https://github.com/user-attachments/assets/1bac9488-abed-4b95-b518-b466548c20d2)

![Image](https://github.com/user-attachments/assets/ef66c3bf-ad97-46f2-bb79-31a70f3ed4c5)
This one I cannot add 3 digits after comma

![Image](https://github.com/user-attachments/assets/2ad2ed49-e748-40dd-a9f3-9cd246d0db4b)

I suppose the calculation is done correctly with 9.975% which, in invoice above would display a total of $344.925 before rounding up, and then hiding last digit as is without rounding up

Can you confirm this and tell me if a fix for that can be applied ?

**Comment by alexgauvin** [comment]
Correct rounded amount is displayed on the main dahsboard, invoices list, payment window and PDF.
Seems like the only place it's not correct is on the invoice page itself (not PDF)

![Image](https://github.com/user-attachments/assets/0337ceb9-384c-4a57-a30a-a96ef7f9e317)

Full payment applied over invoice completely clear the amount. So, I tend to believe that the amount displayed at the bottom of the invoice page is not rounding up as it should be. As I mentionned previously, it probably keeps the amount of $ 344.925000 and display (without rounding) the first 2 decimals after coma, hence  $344.92(5000).

**Comment by beganovich** [comment]
Fixed in https://github.com/invoiceninja/ui/pull/2473.

**Comment by alexgauvin** [comment]
Hi, 

This issue persists on my end. The tax rounding is wrong in ReactUI. 

![Image](https://github.com/user-attachments/assets/9276e15d-2b4b-4c10-ba57-3d99b16f6f37)

**Comment by beganovich** [comment]
Resolved in #2503.
