### ISSUE TITLE
Cant add payment schedule - popup disappears

### ISSUE THREAD

**Issue by Amtech281** [invoiceninja/ui#2685]
## Setup
- Version: v5.12.22
- Environment: Selfh hosted

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
yes, on https://react.invoicing.co/demo happens the same

## Describe the bug

I cant create a payment schedule. When I click in 2nd step on "Schedule" then quickly a popup appears and disappears.

see video

https://github.com/user-attachments/assets/235127c8-0b5c-4e32-b7b7-2ee1c5aa828b

**Comment by Amtech281** [comment]
@Civolilah I see in the demo on your site the bug is still here and as I understand there is no release yet and the docker image is not updated?

**Comment by Civolilah** [comment]
> [@turbo124](https://github.com/turbo124) [@Civolilah](https://github.com/Civolilah) do you know when you plan to fix this issue, so that payment schedules work?

@Amtech281 I just jumped into production and followed your path for the issue. It seems to me that the fix is already live. I hope it is fixed for you as well.

**Comment by amtechacc244DEV** [comment]
@Civolilah we tested it on a new local instance. problem remains, still here

<img width="2400" height="1364" alt="Image" src="https://github.com/user-attachments/assets/1856ac8f-4f9f-469c-8f4f-88ed06fd33ab" />

**Comment by amtechacc244DEV** [comment]
@turbo124 no, see my message above. On your demo site all is working
But not when we installed the newest self hosting version.

**Comment by turbo124** [comment]
I've tested in .28 and it works there

**Comment by turbo124** [comment]
We do inject the partial amount when we generate the invoice. So this may be a "timing" issue.

When you first create the invoice, the balance will be on the swiss qr code.

As each invoice is generated, this will update and use the partial amounts.
